### ISSUE TITLE
Feature request: Remember last state on browser restart

### ISSUE THREAD

**Issue by Fressikus** [wakeuteu/socksproxy-firefox-addon#6]
It would be great if the addon could remember it's last used state when the browser closes and reopens. Currently it always starts with socks proxy off, even when you closed the browser with the proxy setting set to "on".

**Comment by wakeuteu** [comment]
Hi, 
Thanks for the suggestion. I actually read again firefox article and my code seems to be already correct to carry over state over Firefox restart. 
I'm working on it.

**Comment by wakeuteu** [comment]
Hi,
Sorry I left the code alone for a while... I might have just fixed that in commit b23ba8142fc033e970c1f2dc0a7909d0820e6e36 (v1.1.1). I left it opened because I was not able to reproduce this so I will wait for your feedback (I've not published the version on addons center yet but will do before end of week.
Edit: I believe this is actually the same behavior as described in Issue #7 . Definitive fix is the same, persistence of the currentState (enabled/disabled).
